require("huez").setup({
  fallback = "catppuccin",
  suppress_messages = true,
  theme_config_module = nil,
  exclude = {
    "default",
    "desert",
    "evening",
    "industry",
    "koehler",
    "morning",
    "murphy",
    "pablo",
    "peachpuff",
    "ron",
    "shine",
    "slate",
    "torte",
    "zellner",
    "blue",
    "darkblue",
    "delek",
    "quiet",
    "elflord",
    "habamax",
    "lunaperche",
    "zaibatsu",
    "wildcharm",
    "sorbet",
    "vim",
    "minicyan",
    "retrobox",
    "randomhue",
  },
  picker = {
    themes = {
      layout = "top",
      opts = {},
    },
    favorites = {
      layout = "top",
      opts = {},
    },
    live = {
      layout = "top",
      opts = {},
    },
    ensured = {
      layout = "top",
      opts = {},
    },
  },
})
